<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'HumusUser\Module'                                     => __DIR__ . '//Module.php',
    'HumusUser\Util\Exception\InvalidArgumentException'    => __DIR__ . '//src/HumusUser/Util/Exception/InvalidArgumentException.php',
    'HumusUser\Util\Exception'                             => __DIR__ . '//src/HumusUser/Util/Exception.php',
    'HumusUser\Util\Password'                              => __DIR__ . '//src/HumusUser/Util/Password.php',
    'HumusUser\Service\User'                               => __DIR__ . '//src/HumusUser/Service/User.php',
    'HumusUser\Service\Exception\InvalidArgumentException' => __DIR__ . '//src/HumusUser/Service/Exception/InvalidArgumentException.php',
    'HumusUser\Service\Exception'                          => __DIR__ . '//src/HumusUser/Service/Exception.php',
    'HumusUser\Service\UserInterface'                      => __DIR__ . '//src/HumusUser/Service/UserInterface.php',
    'HumusUser\Options\Options'                            => __DIR__ . '//src/HumusUser/Options/Options.php',
    'HumusUser\Form\Base'                                  => __DIR__ . '//src/HumusUser/Form/Base.php',
    'HumusUser\Form\Register'                              => __DIR__ . '//src/HumusUser/Form/Register.php',
    'HumusUser\Model\User'                                 => __DIR__ . '//src/HumusUser/Model/User.php',
    'HumusUser\Model\UserInterface'                        => __DIR__ . '//src/HumusUser/Model/UserInterface.php',
    'HumusUser\Controller\UserController'                  => __DIR__ . '//src/HumusUser/Controlller/UserController.php',
);